### ISSUE TITLE
Install Issues / Broken Script

### ISSUE THREAD

**Issue by callaginn** [qferr/mjml-twig#1]
This script initially looked promising; however, it appears to be broken / non-functional. I'm using the instructions in the Medium article: https://medium.com/@qferrer/using-mjml-with-twig-cccea9af0086

When you try to install it, you'll get this error:
<img width="698" alt="Screen Shot 2020-06-22 at 12 31 05 PM" src="https://user-images.githubusercontent.com/2430211/85317611-41bfe800-b484-11ea-95ad-c9d68331c63d.png">

The ONLY way I could install it was downgrade to Twig 2.0 and add minimum-stability: dev to my composer.json file.

And if you try to run it, you get this error:
<img width="974" alt="Screen Shot 2020-06-22 at 12 31 37 PM" src="https://user-images.githubusercontent.com/2430211/85317655-5a300280-b484-11ea-866c-5328fbc322c5.png">

No matter what I tried, I couldn't get this script to function at all. Even tried switching to your "https://github.com/qferr/mjml-php" extension -- but ran into the exact same issue.

### Technology Stack
Twig: 2.12.5
PHP: 7.4.6

**Comment by callaginn** [comment]
Since this script didn't work and we don't want to depend on the free official API, I threw together a simpler PHP solution:

``` php
$home = `printf ~`;
putenv("HOME=$home");
putenv('PATH=$PATH:/bin:/usr/bin:/usr/local/bin:$HOME/bin');

function mjml2html($mjml) {
    $mjml = customMJML($mjml);
    $temp = tempnam('', '');
    file_put_contents($temp, $mjml);
    $html = shell_exec('. ~/.bashrc; mjml ' . $temp . ' --config.minify true');
    unlink($temp);
    return $html;
}
```

You can initialize like this
``` php
$html = mjml2html($mjml);
echo $html;
```

Let me know if this helps anyone -- cause there's very little easy-to-use code out there.

**Comment by qferr** [comment]
Hello @callaginn. Sorry, I forgot to create a release to use the package in production. Could you try again ? You should clear composer cache if it doesn't work. Best regards.

**Comment by callaginn** [comment]
Is this compatible with Twig v3? I went ahead and re-upgraded Twig, so am trying not to downgrade yet again.

Anyways, this fixed the InvalidArgumentException issue, but still gives me a Twig compatibility error:
``` bash
Using version ^1.0 for qferr/mjml-twig
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for qferr/mjml-twig ^1.0 -> satisfiable by qferr/mjml-twig[1.0.0].
    - qferr/mjml-twig 1.0.0 requires twig/twig ~2.0 -> satisfiable by twig/twig[2.x-dev, v2.0.0, v2.1.0, v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2, v2.12.3, v2.12.4, v2.12.5, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.8.0, v2.8.1, v2.9.0] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by qferr** [comment]
Sorry, the project does not support Twig v3. I will take a look at the new version of Twig to see if it would be easy to integrate.

**Comment by qferr** [comment]
Hello @callaginn. Could you test the integration of Twig v3 by using the branch `dev-support-twig-v3`:
```json
"require": {
    "qferr/mjml-twig": "dev-support-twig-v3"
}
```
Let me know if it works well with your project. You may set the minimum stability to dev to test it.

**Comment by callaginn** [comment]
This didn't work for me either. Kept getting this error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package qferr/mjml-twig dev-support-twig-v3 exists as qferr/mjml-twig[1.0.0, dev-master] but these are rejected by your constraint.
```
